/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hurufijaiyah;

import java.awt.AlphaComposite;
import static java.awt.AlphaComposite.Clear;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
 

/**
 *
 * @author User
 */
public class Frame2 extends javax.swing.JFrame {
   String Angka = "";
   String jawaban = "";
   String Betul = "";
   String Benar="";
   String Salah="";
   String Soal[] = {""};
    private boolean playing;
   
    
    public Frame2() {
        initComponents();
        A.setText(""+Soal[0]);
        B.setText(""+Soal[0]);
        C.setText(""+Soal[0]);
        
         Toolkit tk = Toolkit.getDefaultToolkit();
       int xsize = (int) tk.getScreenSize().getWidth();
       int ysize = (int) tk.getScreenSize().getHeight();
       this.setSize(xsize, ysize);
    }
    public void Clear() 
    {
        GrupB.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupB = new javax.swing.ButtonGroup();
        PermainanPanel = new javax.swing.JPanel();
        btnSelanjutnya = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        C1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        btnCek = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Soal1 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PermainanPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PermainanPanel.setMaximumSize(new java.awt.Dimension(1499, 784));
        PermainanPanel.setMinimumSize(new java.awt.Dimension(1499, 830));
        PermainanPanel.setLayout(null);

        btnSelanjutnya.setBackground(new java.awt.Color(255, 255, 153));
        btnSelanjutnya.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        btnSelanjutnya.setForeground(new java.awt.Color(51, 102, 0));
        btnSelanjutnya.setText("Selanjutnya");
        btnSelanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaActionPerformed(evt);
            }
        });
        PermainanPanel.add(btnSelanjutnya);
        btnSelanjutnya.setBounds(870, 720, 460, 80);

        jPanel7.setMinimumSize(new java.awt.Dimension(510, 510));

        C1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\1.png")); // NOI18N

        B1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\3.png")); // NOI18N

        A1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\9.png")); // NOI18N

        GrupB.add(A);
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        GrupB.add(B);
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        GrupB.add(C);
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C1)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B1)
                .addGap(187, 187, 187))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(B1)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(B)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(A))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(C)))
                .addGap(120, 120, 120))
        );

        PermainanPanel.add(jPanel7);
        jPanel7.setBounds(840, 170, 510, 520);

        btnCek.setBackground(new java.awt.Color(255, 255, 153));
        btnCek.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        btnCek.setForeground(new java.awt.Color(51, 102, 0));
        btnCek.setText("Cek Hasil");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        PermainanPanel.add(btnCek);
        btnCek.setBounds(170, 710, 460, 80);

        Soal1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\Alif.png")); // NOI18N
        Soal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Soal1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Soal1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(Soal1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        PermainanPanel.add(jPanel6);
        jPanel6.setBounds(160, 170, 510, 520);

        jLabel69.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bgpo.png")); // NOI18N
        jLabel69.setText("jLabel6");
        PermainanPanel.add(jLabel69);
        jLabel69.setBounds(-30, 0, 1470, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(PermainanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PermainanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        jawaban = "C";
    }//GEN-LAST:event_CActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        jawaban = "A";
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
       jawaban = "B";
    }//GEN-LAST:event_BActionPerformed

    private void btnSelanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaActionPerformed
        Frame3 frame3 = new Frame3();
        frame3.setVisible(true);        
    }//GEN-LAST:event_btnSelanjutnyaActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        Angka="";
        if(Angka==""){
        
                if(C.isSelected()){
                    Benar = "Alhamdulillah, kamu menjawab benarr.. hebat!!";
                    JOptionPane.showMessageDialog(null, Benar);
                }else{
                
                    Salah ="Maaf ya kamu masih salah.. coba lagi yuk!!";
                }

        }
         if(Angka==""){
        
                if(A.isSelected()){
                    Salah = "Maaf ya kamu masih salah.. coba lagi yuk!!";
                    JOptionPane.showMessageDialog(null, Salah);
                }else{
                
                    Benar = "Alhamdulillah, kamu menjawab benarr.. hebat!!";
                }

        }
         if(Angka==""){
        
                if(B.isSelected()){
                    Salah = "Maaf ya kamu masih salah.. coba lagi yuk!!";
                    JOptionPane.showMessageDialog(null, Salah);
                }else{
                
                    Benar = "Alhamdulillah, kamu menjawab benarr.. hebat!!";
                }
                Clear();

        }
        
        Clear();
    }//GEN-LAST:event_btnCekActionPerformed

    private void Soal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Soal1MouseClicked
        File file = new File("src//wav//Alif.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
        
  
    }//GEN-LAST:event_Soal1MouseClicked
    
    /**
     * @param args the command line arguments
     * @throws javax.sound.sampled.UnsupportedAudioFileException
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JLabel A1;
    private javax.swing.JRadioButton B;
    private javax.swing.JLabel B1;
    private javax.swing.JRadioButton C;
    private javax.swing.JLabel C1;
    private javax.swing.ButtonGroup GrupB;
    private javax.swing.JPanel PermainanPanel;
    private javax.swing.JLabel Soal1;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnSelanjutnya;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
