/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hurufijaiyah;

import java.awt.AlphaComposite;
import static java.awt.AlphaComposite.Clear;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Frame5 extends javax.swing.JFrame {
   String angka = "";
   String Angka = "";
   String jawaban = "";
   String Betul = "";
   String Benar="";
   String Salah="";
   String Soal[] = {""};
   
    
    public Frame5() {
        initComponents();
        A.setText(""+Soal[0]);
        B.setText(""+Soal[0]);
        C.setText(""+Soal[0]);
        
         Toolkit tk = Toolkit.getDefaultToolkit();
       int xsize = (int) tk.getScreenSize().getWidth();
       int ysize = (int) tk.getScreenSize().getHeight();
       this.setSize(xsize, ysize);
    }
    public void Clear() 
    {
        GrupB.clearSelection();
    }
    /**
     * Creates new form Frame5
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupB = new javax.swing.ButtonGroup();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        A = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();
        btnSelanjutnya = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setLayout(null);

        jPanel18.setMinimumSize(new java.awt.Dimension(510, 510));

        jLabel53.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\16.png")); // NOI18N

        jLabel54.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\17.png")); // NOI18N

        jLabel55.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\24.png")); // NOI18N

        GrupB.add(B);

        GrupB.add(C);

        GrupB.add(A);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54)
                .addGap(187, 187, 187))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(B)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(C))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(A)))
                .addGap(120, 120, 120))
        );

        jPanel17.add(jPanel18);
        jPanel18.setBounds(840, 170, 510, 520);

        jLabel56.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\Screenshot 2022-05-24 200918.png")); // NOI18N
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel17.add(jPanel19);
        jPanel19.setBounds(160, 180, 510, 520);

        btnCek.setBackground(new java.awt.Color(255, 255, 153));
        btnCek.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        btnCek.setForeground(new java.awt.Color(51, 102, 0));
        btnCek.setText("Cek Hasil");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        jPanel17.add(btnCek);
        btnCek.setBounds(190, 720, 460, 80);

        btnSelanjutnya.setBackground(new java.awt.Color(255, 255, 153));
        btnSelanjutnya.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        btnSelanjutnya.setForeground(new java.awt.Color(51, 102, 0));
        btnSelanjutnya.setText("Selanjutnya");
        btnSelanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaActionPerformed(evt);
            }
        });
        jPanel17.add(btnSelanjutnya);
        btnSelanjutnya.setBounds(870, 720, 460, 80);

        jLabel72.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bgpo.png")); // NOI18N
        jLabel72.setText("jLabel6");
        jPanel17.add(jLabel72);
        jLabel72.setBounds(0, 0, 1440, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1433, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        Angka = "";
 
        if(Angka==""){

            if(B.isSelected()){
                Benar = "Alhamdulillah, kamu menjawab benarr.. hebat!!";
                JOptionPane.showMessageDialog(null, Benar);
            }else{

                Salah ="Maaf ya kamu masih salah.. coba lagi yuk!!";
            }
            

        }
        if(Angka==""){

            if(C.isSelected()){
                Salah ="Maaf ya kamu masih salah.. coba lagi yuk!!";
                JOptionPane.showMessageDialog(null, Salah);
            }else{

                Benar ="Alhamdulillah, kamu menjawab benarr.. hebat!!";
            }
       
     
        }
        if(Angka==""){

            if(A.isSelected()){
                Salah = "Maaf ya kamu masih salah.. coba lagi yuk!!";
                JOptionPane.showMessageDialog(null, Salah);
            }else{

                Benar = "Alhamdulillah, kamu menjawab benarr.. hebat!!";
            }
       
        }
        
        Clear();
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnSelanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaActionPerformed
        Frame6 frame6 = new Frame6();
        frame6.setVisible(true);
    }//GEN-LAST:event_btnSelanjutnyaActionPerformed

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
         File file = new File("src//wav//Dzod.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel56MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.ButtonGroup GrupB;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnSelanjutnya;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    // End of variables declaration//GEN-END:variables
}
