/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hurufijaiyah;

import java.awt.Toolkit;
import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    
    Panel_Welcome a;
     /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
         
        a = new Panel_Welcome();
        
        MengenalHijaiyah.add(a);
        
        
        a.setVisible(true);
        welcomePanel.setVisible(false);
        
       
        
       //Tampilan FULL SCREEN 
       Toolkit tk = Toolkit.getDefaultToolkit();
       int xsize = (int) tk.getScreenSize().getWidth();
       int ysize = (int) tk.getScreenSize().getHeight();
       this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTampilanAwal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TampilanAwal = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        Permainan = new javax.swing.JButton();
        MengenalHijaiyah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 0));
        jButton1.setText("Mulai");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("American Purpose STRIPE 1", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("MENGENAL HURUF");

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("HiJAiYAH");

        TampilanAwal.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bbn.jpg")); // NOI18N
        TampilanAwal.setMaximumSize(new java.awt.Dimension(1961, 1080));
        TampilanAwal.setMinimumSize(new java.awt.Dimension(1961, 1080));
        TampilanAwal.setPreferredSize(new java.awt.Dimension(1961, 1080));

        javax.swing.GroupLayout jTampilanAwalLayout = new javax.swing.GroupLayout(jTampilanAwal);
        jTampilanAwal.setLayout(jTampilanAwalLayout);
        jTampilanAwalLayout.setHorizontalGroup(
            jTampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTampilanAwalLayout.createSequentialGroup()
                .addGroup(jTampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTampilanAwalLayout.createSequentialGroup()
                        .addGap(690, 690, 690)
                        .addComponent(jButton1))
                    .addGroup(jTampilanAwalLayout.createSequentialGroup()
                        .addGap(643, 643, 643)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jTampilanAwalLayout.createSequentialGroup()
                        .addGap(633, 633, 633)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1177, Short.MAX_VALUE))
            .addGroup(jTampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTampilanAwalLayout.createSequentialGroup()
                    .addContainerGap(450, Short.MAX_VALUE)
                    .addComponent(TampilanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );
        jTampilanAwalLayout.setVerticalGroup(
            jTampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTampilanAwalLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(jTampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTampilanAwalLayout.createSequentialGroup()
                    .addGap(0, 53, Short.MAX_VALUE)
                    .addComponent(TampilanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jTampilanAwal);
        jTampilanAwal.setBounds(0, 0, 2000, 900);

        welcomePanel.setMaximumSize(new java.awt.Dimension(1499, 2000));
        welcomePanel.setMinimumSize(new java.awt.Dimension(1499, 800));
        welcomePanel.setOpaque(false);
        welcomePanel.setLayout(null);

        Permainan.setBackground(new java.awt.Color(255, 255, 153));
        Permainan.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        Permainan.setForeground(new java.awt.Color(51, 102, 0));
        Permainan.setText("Permainan Menghafal Hijaiyah");
        Permainan.setBorder(null);
        Permainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermainanActionPerformed(evt);
            }
        });
        welcomePanel.add(Permainan);
        Permainan.setBounds(400, 570, 990, 80);

        MengenalHijaiyah.setBackground(new java.awt.Color(255, 255, 153));
        MengenalHijaiyah.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        MengenalHijaiyah.setForeground(new java.awt.Color(51, 102, 0));
        MengenalHijaiyah.setText("Mengenal Hijaiyah");
        MengenalHijaiyah.setBorder(null);
        MengenalHijaiyah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MengenalHijaiyahMouseClicked(evt);
            }
        });
        MengenalHijaiyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MengenalHijaiyahActionPerformed(evt);
            }
        });
        welcomePanel.add(MengenalHijaiyah);
        MengenalHijaiyah.setBounds(580, 390, 620, 80);

        jLabel7.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("SELAMAT DATANG");
        welcomePanel.add(jLabel7);
        jLabel7.setBounds(610, 170, 680, 130);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bgpo.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(1445, 794));
        jLabel6.setMinimumSize(new java.awt.Dimension(1445, 794));
        jLabel6.setPreferredSize(new java.awt.Dimension(1445, 794));
        welcomePanel.add(jLabel6);
        jLabel6.setBounds(-40, 0, 3000, 1010);

        getContentPane().add(welcomePanel);
        welcomePanel.setBounds(0, 0, 1833, 1000);
        welcomePanel.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setMaximumSize(new java.awt.Dimension(1499, 784));
        jPanel3.setMinimumSize(new java.awt.Dimension(1499, 784));
        jPanel3.setPreferredSize(new java.awt.Dimension(1499, 784));
        jPanel3.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\8.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\3.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\5.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\7.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\4.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\6.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\2.png")); // NOI18N
        jLabel14.setText("jLabel1");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\1.png")); // NOI18N
        jLabel15.setText("jLabel1");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\16.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\15.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\14.png")); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\13.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\12.png")); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\11.png")); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\10.png")); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\9.png")); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\24.png")); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\23.png")); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\22.png")); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\21.png")); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\20.png")); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\19.png")); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\18.png")); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\17.png")); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\30.png")); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\29.png")); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\28.png")); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\27.png")); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\26.png")); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\Hijaiyyah\\25.png")); // NOI18N
        jLabel37.setText("jLabel1");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Kembali");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel28)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel29)
                    .addComponent(jLabel21)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(60, 120, 1290, 640);

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bgpo.png")); // NOI18N
        jLabel9.setText("jLabel6");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 0, 1440, 830);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1440, 830);

        jPanel21.setLayout(null);

        jPanel22.setMinimumSize(new java.awt.Dimension(510, 510));

        jLabel58.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\Hijaiyyah\\12.png")); // NOI18N

        jLabel59.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\Hijaiyyah\\11.png")); // NOI18N

        jLabel60.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\Hijaiyyah\\13.png")); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addGap(187, 187, 187))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addGap(20, 20, 20)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60))
                .addGap(120, 120, 120))
        );

        jPanel21.add(jPanel22);
        jPanel22.setBounds(840, 170, 510, 520);

        jLabel61.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\Hijaiyyah\\syin.png")); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel21.add(jPanel23);
        jPanel23.setBounds(160, 180, 510, 520);

        jPanel24.setBackground(new java.awt.Color(255, 255, 153));
        jPanel24.setToolTipText("");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(102, 204, 0));
        jLabel62.setText("Menu");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel62)
                .addGap(120, 120, 120))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel24);
        jPanel24.setBounds(1000, 750, 354, 53);

        jLabel73.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 4\\Pemrograman Objek 2\\Tubes\\hurufIjaiyah\\bgpo.png")); // NOI18N
        jLabel73.setText("jLabel6");
        jPanel21.add(jLabel73);
        jLabel73.setBounds(0, 0, 1440, 830);

        getContentPane().add(jPanel21);
        jPanel21.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        File file = new File("src//wav//Alif.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();     
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
       jTampilanAwal.setVisible(false);
        welcomePanel.setVisible(true);
        a.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

    private void MengenalHijaiyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MengenalHijaiyahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MengenalHijaiyahActionPerformed

    private void MengenalHijaiyahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MengenalHijaiyahMouseClicked
        MengenalHijaiyah.setVisible(false);
        a.setVisible(true);
        welcomePanel.setVisible(false);
    }//GEN-LAST:event_MengenalHijaiyahMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MengenalHijaiyah.setVisible(true);
        a.setVisible(false);
        welcomePanel.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void PermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermainanActionPerformed

        Frame2 frame2 = new Frame2();
        frame2.setVisible(true);

        
    }//GEN-LAST:event_PermainanActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
         File file = new File("src//wav//ba.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         File file = new File("src//wav//Ta.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        File file = new File("src//wav//Tsa.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         File file = new File("src//wav//Jim.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         File file = new File("src//wav//Ha.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        File file = new File("src//wav//Kha.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         File file = new File("src//wav//Da.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        File file = new File("src//wav//Dzal.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
         File file = new File("src//wav//Ra.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
         File file = new File("src//wav//Zai.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        File file = new File("src//wav//Sin.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
         File file = new File("src//wav//Syin.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
         File file = new File("src//wav//Shad.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
         File file = new File("src//wav//Dzod.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
         File file = new File("src//wav//Tha.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
         File file = new File("src//wav//Dho.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
         File file = new File("src//wav//'ain.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
         File file = new File("src//wav//Ghain.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
         File file = new File("src//wav//Fa.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
         File file = new File("src//wav//Qaf.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
         File file = new File("src//wav//Kaf.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
         File file = new File("src//wav//Lam.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
         File file = new File("src//wav//Mim.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
         File file = new File("src//wav//Nun.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
         File file = new File("src//wav//wau.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
         File file = new File("src//wav//Haa.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
         File file = new File("src//wav//Lam Alif.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
         File file = new File("src//wav//Hamzah.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
         File file = new File("src//wav//Ya.wav");
        AudioInputStream audioStream = null;
       try {
           audioStream = AudioSystem.getAudioInputStream(file);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        Clip clip = null;
       try {
           clip = AudioSystem.getClip();
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           clip.open(audioStream);
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        clip.start();    
    }//GEN-LAST:event_jLabel32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MengenalHijaiyah;
    private javax.swing.JButton Permainan;
    private javax.swing.JLabel TampilanAwal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jTampilanAwal;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
